---
yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"

# these rules are for GitHub Super-Linter Action (instead of standard YamlLint).
# GitHub Super-Linter Action: https://github.com/super-linter/super-linter
# YamlLint docs: https://yamllint.readthedocs.io/en/stable/rules.html
rules:
  anchors:
    forbid-undeclared-aliases: true
    forbid-duplicated-anchors: true
    # forbid-unused-anchors: true # not supported as of v5.3.1
  braces:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 1
    max-spaces-inside-empty: 5
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 1
    max-spaces-inside-empty: 5
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation: enable
  document-end: disable
  document-start: disable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
  empty-values:
    level: warning
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  float-values:
    forbid-inf: false
    forbid-nan: false
    forbid-scientific-notation: false
    require-numeral-before-decimal: true
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: consistent
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates: enable
  key-ordering: disable
  line-length:
    level: warning
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  # `quoted-strings` rule disabled due to instability of YamlLinter in v5.3.1 action
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    allowed-values: [ "true", "false" ]
    check-keys: false
    ignore: |
      docker-compose.yml
