name: "🐞 Bug report"
description: "Create a bug report to help us improve."
labels: [ "bug" ]
type: "bug"
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > **Before you fill in this bug report**...
        > Please search [open/closed issues](issues?q=is%3Aissue) before submitting, the issue might be already known and fixed before.
  - type: input
    id: reporter
    attributes:
      label: "Original Reporter"
      description: "Tag the person who first reported this bug, or use `@your-github-username` to indicate yourself."
      placeholder: "@github-username (or name)"
    validations:
      required: true
  - type: input
    id: app-details
    attributes:
      label: "App Details"
      description: "The app version (`x.x.x`); see [milestones](../milestones) for known released versions."
      placeholder: "1.2.3"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What is the issue?"
      placeholder: "A clear and concise description of the bug. What is expected? Screenshots?"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce the Behavior"
      description: "Step-by-step instruction to reproduce the bug/behavior."
      placeholder: |
        1. Go '...'
        2. Do '...'
        3. Expected '...', but actual is '...'
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
      placeholder: "e.g. stacktrace, logs, other related issues, etc."
    validations:
      required: false
