name: "🚀 Enhancement request"
description: "Suggest an improvement for this project."
labels: [ "enhancement" ]
type: "feature"
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > **Before you fill in this enhancement request**...
        > Please search [open/closed issues](../issues?q=is%3Aissue) before submitting, the issue might have been requested.
  - type: input
    id: requester
    attributes:
      label: "Original Requester"
      description: "Tag the person who first requested this feature, or use `@your-github-username` to indicate yourself."
      placeholder: "@github-username (or name)"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Describe the Enhancement You Would Like"
      description: >
        A clear and concise description of what the problem is and what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives You've Considered"
      description: >
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
