name: REVIEW-PR

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened ]

jobs:
  review-title:
    name: Semantic Pull Request
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
